services:
  php:
    container_name: php
    image: maho/php
    build:
      dockerfile: .docker/php.Dockerfile
    environment:
      - SERVER_NAME=demo.mahocommerce.com
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
      - ${HTTPS_PORT:-443}:443/udp
    restart: unless-stopped
    volumes:
      - .:/app
      - .docker/data:/data
      - .docker/config:/config
    user: "1000:1000"
    tty: true
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=maho
      - MYSQL_USER=maho
      - MYSQL_PASSWORD=maho
      - MYSQL_ROOT_PASSWORD=Jnsdnao374dfbNJsdns
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
